---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: um-experiment
# description will be included in the image's metadata
description: Testing and experimenting with Ultramarine images

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ultramarine-linux/base-bootc
image-version: 44 # latest is also supported if you want new updates ASAP

modules:
  - type: signing
  - type: dnf
    install:
      packages:
        - ghostty # VSCodium, alternative to VSCode
